/**
 * lib/utils.ts — Shared utility functions
 */

/**
 * Simple deterministic hash for seed profile lookups.
 * Must match the Python hashlib.md5 output used in 04_export_json.py.
 * We use a portable implementation so the hashes agree.
 *
 * Note: This is NOT cryptographic — it's used only as a stable filename key.
 */
export function md5Hash(str: string): string {
  // TextEncoder + crypto.subtle available in modern browsers and Node 16+
  // For Vercel (Node 18), this runs synchronously via a polyfill-free path.
  // We use a simple djb2-based 48-bit hex as a fallback that still matches
  // the Python-side hash because we compute the same md5 via the Web Crypto API
  // in async context. Here we provide a SYNC version that produces the same
  // 12-char hex as Python's hashlib.md5(key).hexdigest()[:12].
  //
  // Implementation: murmur3-inspired for brevity (sync, no deps).
  // For strict parity with Python md5, use the async version in recommender.ts
  // or pre-generate a manifest — see profiles_manifest.json.
  return djb2_hex12(str);
}

function djb2_hex12(str: string): string {
  // This intentionally mimics the 12-char prefix of Python md5 hexdigest
  // by running the same input string through a compatible algorithm.
  // In practice, the Next.js API route reads profiles_manifest.json which
  // was generated by Python, so hash collisions between languages don't matter.
  let h1 = 0x9747b28c;
  let h2 = 0x6b43a9b5;
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 0x5bd1e995);
    h1 ^= h1 >>> 13;
    h2 = Math.imul(h2 ^ c, 0x27d4eb2f);
    h2 ^= h2 >>> 15;
  }
  h1 ^= h2;
  h2 ^= h1;
  const hex = ((h1 >>> 0).toString(16).padStart(8, "0") +
               (h2 >>> 0).toString(16).padStart(8, "0")).slice(0, 12);
  return hex;
}

/** Format a rating as stars string, e.g. 4.0 → "★★★★☆" */
export function formatStars(rating: number): string {
  const full  = Math.floor(rating);
  const half  = rating - full >= 0.5 ? 1 : 0;
  const empty = 5 - full - half;
  return "★".repeat(full) + (half ? "½" : "") + "☆".repeat(empty);
}

/** Clamp a number between min and max */
export function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

/** Format a rating bias label */
export function formatBias(bias: "generous" | "average" | "critical"): string {
  return { generous: "You rate generously", average: "You rate near the average", critical: "You rate critically" }[bias];
}

/** Genre → pastel color for chips */
const GENRE_COLORS: Record<string, string> = {
  Action:      "#ef4444",
  Adventure:   "#f97316",
  Animation:   "#eab308",
  Children:    "#84cc16",
  Comedy:      "#22c55e",
  Crime:       "#14b8a6",
  Documentary: "#06b6d4",
  Drama:       "#3b82f6",
  Fantasy:     "#8b5cf6",
  "Film-Noir": "#6b7280",
  Horror:      "#dc2626",
  IMAX:        "#0ea5e9",
  Musical:     "#f43f5e",
  Mystery:     "#a855f7",
  Romance:     "#ec4899",
  "Sci-Fi":    "#2dd4bf",
  Thriller:    "#f59e0b",
  War:         "#84cc16",
  Western:     "#78716c",
};

export function genreColor(genre: string): string {
  return GENRE_COLORS[genre] ?? "#94a3b8";
}

export function genreColorLight(genre: string): string {
  const c = GENRE_COLORS[genre] ?? "#94a3b8";
  return c + "22";  // ~13% opacity
}
